Fix Mac build by stripping out duplicate executable slices from Quick Look extension (#1260)
**User-Facing Changes**
None

**Description**
The release build was failing during packaging with:

```
fatal error: /Applications/Xcode_12.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/electron-universal-9qyKr4/Tmp.app/Contents/PlugIns/PreviewExtension.appex/Contents/MacOS/PreviewExtension and /Users/runner/work/***-release-builder/***-release-builder/dist/mac-universal--arm64/Foxglove Studio.app/Contents/PlugIns/PreviewExtension.appex/Contents/MacOS/PreviewExtension have the same architectures (x86_64) and can't be in the same fat output file  failedTask=build stackTrace=Error: Command failed with a non-zero return code (1):
```

This is because of how electron-universal works: it builds an x86_64 and an arm64 version of the app, and merges binaries with lipo. The Quick Look extension introduced in #1187 was copied into both x86_64 and arm64 copies of the app, so lipo refused to merge them because the result would include two copies of each architecture slice.

I fixed this by running `lipo -extract` during the afterPack step (which runs twice, once for x86_64 and once for arm64) to leave only the desired architecture in place, so that the merge step can work properly.