Enable and auto-fix `@typescript-eslint/return-await` (#1411)
Readability by consistency — an async function is now required to `return await` rather than simply `return`ing a promise. This can improve stack traces as described at https://v8.dev/blog/fast-async / https://stackoverflow.com/q/44806135/23649.

Example:

```ts
async function foo() {
  return bar();
}

async function bar() {
  await Promise.resolve();
  throw new Error('BEEP BEEP');
}

foo().catch(error => console.log(error.stack));
```

With `return bar();`:

```
> Error: BEEP BEEP
    at bar (REPL8:3:9)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
```

With `return await bar();`:

```
> Error: BEEP BEEP
    at bar (REPL18:3:9)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async foo (REPL13:2:10)
```

This change can have some negative performance implications: [async functions are slower to call](https://bugs.chromium.org/p/chromium/issues/detail?id=1227083) than non-async functions, and an `await` makes it even slower as it needs to save suspended state. In the tradeoff between stack traces/debuggability and performance, it seems alright to just make authors disable the rule when needed for performance.